name: get version
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    run: |
    TAG=$(curl -s \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      https://api.github.com/repos/${{ github.repository }}/tags \
      | jq -r '.[].name | select(startswith("v"))' \
      | head -n 10)

    echo "tag=$TAG" >> "$GITHUB_OUTPUT"
